---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cloc
  annotations:
    thoth-station.ninja/template-version: 0.6.5
  labels:
    app: thoth
    component: si-cloc
spec:
  templates:
    - name: cloc-from-dir
      inputs:
        parameters:
          - name: "THOTH_SI_CLOC_JOB_ID"
          - name: "THOTH_DOCUMENT_ID"
          - name: "THOTH_SI_CLOC_PACKAGE_NAME"
          - name: "THOTH_SI_CLOC_PACKAGE_VERSION"
          - name: "THOTH_SI_CLOC_PACKAGE_INDEX"
          - name: "THOTH_SI_CLOC_DIR"
      container:
        name: si-cloc
        image: "si-cloc"
        env:
          - name: THOTH_DOCUMENT_ID
            value: "{{inputs.parameters.THOTH_DOCUMENT_ID}}"
          - name: THOTH_SI_CLOC_OUTPUT
            value: "/mnt/workdir/cloc_results"
          - name: THOTH_SI_CLOC_PACKAGE_NAME
            value: "{{inputs.parameters.THOTH_SI_CLOC_PACKAGE_NAME}}"
          - name: THOTH_SI_CLOC_PACKAGE_VERSION
            value: "{{inputs.parameters.THOTH_SI_CLOC_PACKAGE_VERSION}}"
          - name: THOTH_SI_CLOC_PACKAGE_INDEX
            value: "{{inputs.parameters.THOTH_SI_CLOC_PACKAGE_INDEX}}"
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workdir
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
