apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: si-cloc-buildconfig
  annotations:
    description: >
      This is Thoth CLOC Security Indicator BuildConfig, this template is meant to be used by Bots, but could also be
      used by humans...
    openshift.io/display-name: "Thoth: si-cloc BuildConfig"
    version: 0.1.0
    tags: thoth,ai-stacks,si-cloc
    template.openshift.io/documentation-url: https://github.com/Thoth-Station
    template.openshift.io/long-description: >
      This is Thoth CLOC Security indicator BuildConfig, this template is meant to be
      used by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    thoth-station.ninja/template-version: 0.1.0
  labels:
    template: si-cloc-buildconfig
    app: thoth
    component: si-cloc

parameters:
  - description: Git repository for Thoth's Adviser
    displayName: Thoth Adviser git repository
    required: true
    name: GITHUB_URL
    value: "https://github.com/thoth-station/si-cloc"

  - description: Git repository for bandit security indicator
    displayName: Thoth Adviser git reference
    required: true
    name: GITHUB_REF
    value: "master"

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

  - description: Thamos Advise setup tag value
    displayName: THOTH_ADVISE
    required: true
    name: THOTH_ADVISE
    value: "1"

  - description: Thamos Provenance Check setup tag flag
    displayName: THOTH_PROVENANCE_CHECK
    required: true
    name: THOTH_PROVENANCE_CHECK
    value: "0"

  - description: Error fallback flag
    displayName: THOTH_ERROR_FALLBACK
    required: true
    name: THOTH_ERROR_FALLBACK
    value: "1"

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: thoth
        component: si-cloc
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      name: si-cloc
    spec:
      resources:
        limits:
          cpu: 2000m
          memory: 768Mi
        requests:
          cpu: 2000m
          memory: 768Mi
      output:
        to:
          kind: ImageStreamTag
          name: "si-cloc:${IMAGE_STREAM_TAG}"
      runPolicy: Serial
      source:
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-thoth-f32-py38-cloc:latest
          env:
            - name: ENABLE_PIPENV
              value: "1"
            - name: "THOTH_DRY_RUN"
              value: "1"
            - name: "THOTH_ADVISE"
              value: ${THOTH_ADVISE}
            - name: "THAMOS_VERBOSE"
              value: "1"
            - name: "THAMOS_DEBUG"
              value: "0"
            - name: "THAMOS_CONFIG_TEMPLATE"
              value: ".thoth.yaml"
            - name: "THAMOS_CONFIG_EXPAND_ENV"
              value: "1"
            - name: "THOTH_PROVENANCE_CHECK"
              value: ${THOTH_PROVENANCE_CHECK}
            - name: "THOTH_ERROR_FALLBACK"
              value: ${THOTH_ERROR_FALLBACK}
      triggers:
        - imageChange: {}
          type: ImageChange
        - type: "Generic"
          generic:
            secretReference:
              name: generic-webhook-secret
